import pandas as pd
df = pd.read_csv("D:\Python\Dataset_CyberCrime_Sean.csv")
print("First 5 Rows")
print(df.head())
print("\nDataset Info")
print(df.info())
print("\nMissing Values")
print(df.isnull().sum())
df = df.dropna(how="all")
df = df.fillna(0)
df = df.drop_duplicates()
print("\nCleaned Data")
print(df.head())
print("\nTotal Cybercrime Cases:", df["Total"].sum())
max_city = df.loc[df["Total"].idxmax()]
print("\nCity with Highest Cybercrime:")
print(max_city["City"], "-", max_city["Total"])
min_city = df.loc[df["Total"].idxmin()]
print("\nCity with Lowest Cybercrime:")
print(min_city["City"], "-", min_city["Total"])
print("\nAverage Cybercrime Cases:", df["Total"].mean())
print("\nTop 5 Cities with Highest Cybercrime")
print(df.sort_values(by="Total", ascending=False).head())
print("\nTotal Cases by Crime Category")
print(df.drop(columns=["City"]).sum())